fix type definition causing 'error TS2314: Generic type 'Promise<T>' … (#59)
* fix type definition causing 'error TS2314: Generic type 'Promise<T>' requires 1 type argument(s)'